-- Insert summer programs data
INSERT INTO competitions (
  title,
  description,
  full_description,
  deadline,
  level,
  subject,
  category,
  age_limit,
  team_size,
  location,
  format,
  is_free,
  language,
  website_url,
  organizer,
  image_url,
  status,
  featured
) VALUES 
(
  'Pioneer Academics Research Program',
  'Онлайн-исследовательская программа с академическим наставничеством; аккредитована колледжем.',
  'Онлайн-исследовательская программа с академическим наставничеством; аккредитована колледжем. Программа предоставляет старшеклассникам возможность работать с академическими наставниками над исследовательскими проектами.',
  '2025-04-30T23:59:59Z',
  'international',
  'Исследования',
  'Летние программы',
  '10-12 классы',
  'Индивидуально',
  'Онлайн',
  'online',
  false,
  'Английский',
  'https://pioneeracademics.com',
  'Pioneer Academics',
  '/placeholder.svg?height=200&width=300&text=Pioneer',
  'active',
  true
),
(
  'Yale Young Global Scholars (YYGS)',
  '2-недельная программа с направлениями в STEM, гуманитарных и социальных науках.',
  '2-недельная программа с направлениями в STEM, гуманитарных и социальных науках. Престижная программа Йельского университета для талантливых старшеклассников со всего мира.',
  '2025-01-31T23:59:59Z',
  'international',
  'Междисциплинарные',
  'Летние программы',
  '15-18 лет',
  'Индивидуально',
  'Йель, США',
  'offline',
  false,
  'Английский',
  'https://globalscholars.yale.edu',
  'Yale University',
  '/placeholder.svg?height=200&width=300&text=Yale',
  'active',
  true
),
(
  'Summer Science Program (SSP)',
  'Астрофизика, биохимия, геномика и синтетическая химия; участие в реальных научных исследованиях.',
  'Программа по астрофизике, биохимии, геномике и синтетической химии с участием в реальных научных исследованиях. Одна из самых престижных научных программ для старшеклассников.',
  '2025-02-21T23:59:59Z',
  'international',
  'Естественные науки',
  'Летние программы',
  '15-18 лет (11 класс)',
  'Индивидуально',
  'США (разные кампусы)',
  'offline',
  false,
  'Английский',
  'https://summerscience.org',
  'Summer Science Program',
  '/placeholder.svg?height=200&width=300&text=SSP',
  'active',
  true
),
(
  'Lumiere Research Scholar Program',
  'Индивидуальные исследовательские проекты с наставниками из ведущих университетов.',
  'Индивидуальные исследовательские проекты с наставниками из ведущих университетов. Программа позволяет старшеклассникам проводить серьезные исследования под руководством экспертов.',
  '2025-06-01T23:59:59Z',
  'international',
  'Исследования',
  'Летние программы',
  'Старшеклассники',
  'Индивидуально',
  'Онлайн',
  'online',
  false,
  'Английский',
  'https://www.lumiere-education.com',
  'Lumiere Education',
  '/placeholder.svg?height=200&width=300&text=Lumiere',
  'active',
  false
),
(
  'NYAS Junior Academy',
  'Онлайн-программа, где ученики работают в международных командах над STEM-проектами.',
  'Онлайн-программа Нью-Йоркской академии наук, где ученики работают в международных командах над STEM-проектами. Бесплатная программа для развития научных навыков.',
  '2025-07-01T23:59:59Z',
  'international',
  'STEM',
  'Летние программы',
  '13-17 лет',
  'Команда',
  'Онлайн',
  'online',
  true,
  'Английский',
  'https://www.nyas.org',
  'New York Academy of Sciences',
  '/placeholder.svg?height=200&width=300&text=NYAS',
  'active',
  true
),
(
  'MITES Summer (MIT)',
  '6-недельная программа по STEM для учащихся из недостаточно представленных групп.',
  '6-недельная программа MIT по STEM для учащихся из недостаточно представленных групп. Полностью бесплатная программа с проживанием и питанием.',
  '2025-02-28T23:59:59Z',
  'international',
  'STEM',
  'Летние программы',
  '11 класс',
  'Индивидуально',
  'MIT, США',
  'offline',
  true,
  'Английский',
  'https://mites.mit.edu/discover-mites/mites-summer/',
  'MIT',
  '/placeholder.svg?height=200&width=300&text=MIT',
  'active',
  true
),
(
  'LaunchX Entrepreneurship Program',
  'Предпринимательская программа, где учащиеся создают стартапы.',
  'Предпринимательская программа, где учащиеся создают реальные стартапы под руководством опытных менторов. Доступны онлайн и очные форматы.',
  '2025-04-01T23:59:59Z',
  'international',
  'Предпринимательство',
  'Летние программы',
  'Старшеклассники',
  'Команда',
  'Различные локации',
  'hybrid',
  false,
  'Английский',
  'https://www.launchx.com/programs',
  'LaunchX',
  '/placeholder.svg?height=200&width=300&text=LaunchX',
  'active',
  false
),
(
  'Carnegie Mellon Pre-College Programs',
  'Разнообразные программы: искусство, дизайн, наука, технологии, инженерия и математика.',
  'Разнообразные программы Carnegie Mellon: искусство, дизайн, наука, технологии, инженерия и математика. Программы проводятся на кампусе университета.',
  '2025-05-01T23:59:59Z',
  'international',
  'Междисциплинарные',
  'Летние программы',
  'Старшеклассники',
  'Индивидуально',
  'Питтсбург, США',
  'offline',
  false,
  'Английский',
  'https://cmu.edu/pre-college',
  'Carnegie Mellon University',
  '/placeholder.svg?height=200&width=300&text=CMU',
  'active',
  false
),
(
  'Harvard Pre-College Program',
  '2-недельная программа с академическими курсами и проживанием на кампусе.',
  '2-недельная программа Harvard с академическими курсами и проживанием на кампусе. Возможность изучить университетские курсы и познакомиться с жизнью в Гарварде.',
  '2025-03-15T23:59:59Z',
  'international',
  'Академические курсы',
  'Летние программы',
  '14-18 лет',
  'Индивидуально',
  'Harvard, США',
  'offline',
  false,
  'Английский',
  'https://summer.harvard.edu/high-school-programs/pre-college-program/',
  'Harvard University',
  '/placeholder.svg?height=200&width=300&text=Harvard',
  'active',
  true
),
(
  'UC Berkeley Pre-College Scholars Program',
  'Виртуальные и очные треки; есть Летняя академия компьютерных наук.',
  'Программа UC Berkeley с виртуальными и очными треками, включая специальную Летнюю академию компьютерных наук. Различные форматы участия.',
  '2025-06-03T23:59:59Z',
  'international',
  'Компьютерные науки',
  'Летние программы',
  '16-17 лет',
  'Индивидуально',
  'Berkeley, CA, США',
  'hybrid',
  false,
  'Английский',
  'https://precollege.berkeley.edu',
  'UC Berkeley',
  '/placeholder.svg?height=200&width=300&text=Berkeley',
  'active',
  false
),
(
  'Johns Hopkins Pre-College Summer Programs',
  'Онлайн и очные форматы; несколько сессий летом.',
  'Программы Johns Hopkins в онлайн и очных форматах с несколькими сессиями летом. Широкий выбор академических направлений.',
  '2025-05-15T23:59:59Z',
  'international',
  'Академические курсы',
  'Летние программы',
  '10-12 классы',
  'Индивидуально',
  'Балтимор, Мэриленд, США',
  'hybrid',
  false,
  'Английский',
  'https://summer.jhu.edu/programs-courses/pre-college-programs/',
  'Johns Hopkins University',
  '/placeholder.svg?height=200&width=300&text=JHU',
  'active',
  false
),
(
  'Young Founders Lab',
  '100% виртуальная 4-недельная программа по предпринимательству с живыми семинарами.',
  '100% виртуальная 4-недельная программа по предпринимательству с живыми семинарами. Интенсивная программа для развития предпринимательских навыков.',
  '2025-05-12T23:59:59Z',
  'international',
  'Предпринимательство',
  'Летние программы',
  'Старшеклассники',
  'Индивидуально',
  'Онлайн',
  'online',
  false,
  'Английский',
  'https://www.youngfounderslab.org',
  'Young Founders Lab',
  '/placeholder.svg?height=200&width=300&text=YFL',
  'active',
  false
);

-- Insert some sample competitions for other categories
INSERT INTO competitions (
  title,
  description,
  full_description,
  deadline,
  level,
  subject,
  category,
  age_limit,
  team_size,
  location,
  format,
  is_free,
  language,
  website_url,
  organizer,
  image_url,
  status,
  featured
) VALUES 
(
  'Международная олимпиада по математике IMO 2025',
  'Престижная математическая олимпиада для школьников со всего мира',
  'Международная математическая олимпиада (IMO) проводится ежегодно с 1959 года и является самым престижным математическим соревнованием для школьников в мире.',
  '2025-02-15T23:59:59Z',
  'international',
  'Математика',
  'Олимпиады',
  '15-18 лет',
  'Индивидуально',
  'Австралия, Сидней',
  'offline',
  true,
  'Английский, Русский',
  'https://imo-official.org',
  'Международный математический союз',
  '/placeholder.svg?height=200&width=300&text=IMO',
  'active',
  true
),
(
  'AI Hackathon 2025',
  'Интенсивное соревнование по разработке ИИ-решений',
  'Хакатон по искусственному интеллекту для молодых разработчиков. Участники создают инновационные решения с использованием машинного обучения.',
  '2025-01-28T23:59:59Z',
  'national',
  'Информатика',
  'Хакатоны',
  '16-25 лет',
  '2-5 человек',
  'Алматы, Казахстан',
  'hybrid',
  false,
  'Русский, Английский',
  'https://ai-hackathon.kz',
  'Tech Kazakhstan',
  '/placeholder.svg?height=200&width=300&text=AI+Hackathon',
  'active',
  true
);
